### ISSUE TITLE
stacked bars are broken and break normal bars

### ISSUE THREAD

**Issue by srkunze** [zware/codespeed#3]
That's it for Chrome 48.

**Comment by zware** [comment]
This is due to having selected benchmarks that are not run on all selected executables.  If you deselect everything and selectively choose what you want to compare, stacked bars do work, but as soon as you choose something an executable/benchmark combination that doesn't exist, everything does break.

This is an issue with codespeed itself, would you mind reporting it to tobami/codespeed?
